-- Phase 8: e-NACH mandate draft workflow. No NPCI, bank, or aggregator integration.
create table if not exists public.enach_mandates (
 id uuid primary key default gen_random_uuid(), mandate_reference_number uuid not null unique default gen_random_uuid(),
 organization_id uuid not null references public.organizations(id) on delete restrict, customer_id uuid not null references public.customers(id) on delete restrict,
 account_holder_name text not null check(length(trim(account_holder_name))>0),bank_name text not null check(length(trim(bank_name))>0),branch_name text not null check(length(trim(branch_name))>0),account_number text not null check(account_number ~ '^[0-9]{9,18}$'),ifsc_code text not null check(ifsc_code ~ '^[A-Z]{4}0[A-Z0-9]{6}$'),account_type text not null check(account_type in ('savings','current')),
 maximum_debit_amount numeric(14,2) not null check(maximum_debit_amount>0),debit_frequency text not null check(debit_frequency in ('daily','weekly','monthly','quarterly','halfYearly','yearly','asPresented')),
 start_date date not null,end_date date not null check(end_date>start_date),purpose text not null check(length(trim(purpose))>0),sponsor_bank text not null check(length(trim(sponsor_bank))>0),destination_bank text not null check(length(trim(destination_bank))>0),authentication_mode text not null check(authentication_mode in ('netBanking','debitCard','physical')),status text not null default 'draft' check(status in ('draft','pending','approved','rejected','cancelled')),remarks text,
 gateway_reference text,provider_reference text,webhook_payload jsonb,response_payload jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create index if not exists enach_mandates_organization_id_idx on public.enach_mandates(organization_id);create index if not exists enach_mandates_customer_id_idx on public.enach_mandates(customer_id);create index if not exists enach_mandates_status_idx on public.enach_mandates(status);create index if not exists enach_mandates_reference_idx on public.enach_mandates(mandate_reference_number);
drop trigger if exists enach_mandates_set_updated_at on public.enach_mandates;create trigger enach_mandates_set_updated_at before update on public.enach_mandates for each row execute function public.set_updated_at();alter table public.enach_mandates enable row level security;drop policy if exists enach_mandates_authenticated_all on public.enach_mandates;create policy enach_mandates_authenticated_all on public.enach_mandates for all to authenticated using(true) with check(true);grant select,insert,update on public.enach_mandates to authenticated;revoke all on public.enach_mandates from anon;
comment on table public.enach_mandates is 'e-NACH draft workflow records; external processing is not implemented.';